### ISSUE TITLE
Print pattern Y with stars in c language

### ISSUE THREAD

**Issue by rahulparshi** [rahulparshi/Pattern-printing-with-C#7]
Raise a PR to add Y.c file in individual patterns directory.

which will print pattern Y with stars.
```C
Sample input:
5

Output:

*   *
 * *
  *
  *
  *

Sample input:
7

Output:

*     *
 *   *
  * * 
   *
   *
   *
   *
```
Also add a new case to switch statement in Main.c file to print Y pattern.
After adding your code in Main.c file your input and output should look as below.
```C
sample Input
7 2
EY

output

*******  *     *  
*         *   *  
*          * * 
*******     *
*           *
*           *
*******     *
```

**Comment by Avinash369** [comment]
hey what exactly is to be done here?

**Comment by rahulparshi** [comment]
write a C code to print pattern Y refer the sample input and output.

**Comment by rahulparshi** [comment]
@nymika has resolved the issue...
